services:
  postgres:
    image: postgres:15
    container_name: cloudops-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cloudops
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    command: npm run dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres_data:

#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     container_name: cloudops-backend
#     ports:
#       - "3001:3001"
#     depends_on:
#       - postgres
#     environment:
#       - NODE_ENV=development
#       - PORT=3001
#       - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/cloudops?schema=public
#       - JWT_SECRET=your-secret-key-here
#       - JWT_EXPIRES_IN=1d
#       - FRONTEND_URL=http://localhost:3000
#     volumes:
#       - ./backend:/app
#       - /app/node_modules
#     networks:
#       - cloudops-network
#     command: npm run start:dev

#   frontend:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile
#     container_name: cloudops-frontend
#     ports:
#       - "3000:3000"
#     depends_on:
#       - backend
#     environment:
#       - NEXT_PUBLIC_API_URL=http://localhost:3001
#     volumes:
#       - ./frontend:/app
#       - /app/node_modules
#     networks:
#       - cloudops-network
#     command: npm run dev

# networks:
#   cloudops-network:
#     driver: bridge

# volumes:
#   postgres_data:
